# This is the builder container
FROM node:8.12-alpine
WORKDIR /usr/src/app

COPY package.json yarn.lock ./
COPY internals ./internals/
COPY .* ./

RUN apk add --update --no-cache \
    bash \
    lcms2-dev \
    libpng-dev \
    gcc \
    g++ \
    make \
    autoconf \
    automake \
  && rm -rf /var/cache/apk/*\
  && yarn install
